### ISSUE TITLE
Lepton capture

### ISSUE THREAD

**Issue by anjomshoaa** [kekiefer/pylepton#1]
Hi,

I have tried to use pylepton_capture but the output is just a blank image. Also the Lepton is functioning via raspberrypi_video (PureEngineering/LeptonModule) which means camera should be OK. Do you have any idea why this is happening?

Regards
Amin 

Update: solved, the device name was different from the pylepton default. By setting that to spidev01.1, the problem is solved.

**Comment by kekiefer** [comment]
@anjomshoaa, glad you figured it out! For others, if you are using the library directly:

```
...
with Lepton("/dev/spidev0.1") as l:
  ...
```

Or from the example programs, both will accept a command line option `--device=/dev/spidev0.1`.
